### ISSUE TITLE
🏙 Create Cities Dropdown 🏙 

### ISSUE THREAD

**Issue by damla** [patika-hepsiburada-react-bootcamp/odev-4-damla#6]
# To-Do's

- [x] Implement [reactjs-dropdown-component](https://github.com/dbilgili/Custom-ReactJS-Dropdown-Components) as a Cities component.
- [x] Customize style of it.
- [x] Implement CitiesContext.
- [x] Set selected city as "Trabzon".
